### ISSUE TITLE
The script won't run. All dependencies installed 

### ISSUE THREAD

**Issue by AIIX** [Larpon/linuxdeployqt.py#1]
Traceback (most recent call last):
  File "./linuxdeployqt.py", line 579, in <module>
    exedeps = resolve_dependencies(exe)
  File "./linuxdeployqt.py", line 153, in resolve_dependencies
    objdump(executable)
TypeError: objdump() takes exactly 2 arguments (1 given)

./linuxdeployqt.py /home/Aix/release-mycroft-qtapplication/mycroft-qtapplication --qt-base-dir /usr/lib64/qt5 --qml-scan-dir /home/Aix/mycroft-qtapplication --appimage --qml-import "QtQuick 2.0" --qml-import "QtQml.Models 2.2" --qml-import "QtQuick.Controls 1.0" --qml-import "QtQuick.Layouts 1.0" --qml-import "Qt.WebSockets 1.0" --qml-import "QtQuick.Controls.Styles 1.4" --qml-import "QtQuick.Controls 2.0" --appimage -v 3

executable in build dir is also marked executable.

**Comment by AIIX** [comment]
Running a direct objdump from shell on the executable provides the following:
objdump -x /home/Aix/release-mycroft-qtapplication/mycroft-qtapplication

Dynamic Section:
  NEEDED               libQt5Quick.so.5
  NEEDED               libQt5Widgets.so.5
  NEEDED               libQt5Gui.so.5
  NEEDED               libQt5Qml.so.5
  NEEDED               libQt5Network.so.5
  NEEDED               libQt5Core.so.5
  NEEDED               libGL.so.1
  NEEDED               libpthread.so.0
  NEEDED               libstdc++.so.6
  NEEDED               libm.so.6
  NEEDED               libgcc_s.so.1
  NEEDED               libc.so.6
  INIT                 0x0000000000401498
  FINI                 0x0000000000401fd4
  INIT_ARRAY           0x0000000001701ba0
  INIT_ARRAYSZ         0x0000000000000010
  FINI_ARRAY           0x0000000001701bb0
  FINI_ARRAYSZ         0x0000000000000008
  GNU_HASH             0x0000000000400298
  STRTAB               0x00000000004007d8
  SYMTAB               0x00000000004002e0
  STRSZ                0x0000000000000646
  SYMENT               0x0000000000000018
  DEBUG                0x0000000000000000
  PLTGOT               0x0000000001702000
  PLTRELSZ             0x00000000000002d0
  PLTREL               0x0000000000000007
  JMPREL               0x00000000004011c8
  RELA                 0x0000000000400f88
  RELASZ               0x0000000000000240
  RELAENT              0x0000000000000018
  VERNEED              0x0000000000400e88
  VERNEEDNUM           0x0000000000000007
  VERSYM               0x0000000000400e1e

Version References:
  required from libQt5Gui.so.5:
    0x00058a25 0x00 08 Qt_5
  required from libgcc_s.so.1:
    0x0b792650 0x00 07 GCC_3.0
  required from libstdc++.so.6:
    0x056bafd3 0x00 10 CXXABI_1.3
    0x08922974 0x00 06 GLIBCXX_3.4
  required from libQt5Qml.so.5:
    0x00058a25 0x00 05 Qt_5
  required from libc.so.6:
    0x09691a75 0x00 04 GLIBC_2.2.5
  required from libQt5Widgets.so.5:
    0x00058a25 0x00 03 Qt_5
  required from libQt5Core.so.5:
    0x058a2817 0x00 09 Qt_5.7
    0x00058a25 0x00 02 Qt_5

**Comment by AIIX** [comment]
Fixed. Commented out:     
Uncommented: ldd(executable) 
Line 153: #objdump(executable)
Line 154: #return {} 

The Use 'ldd' method for now. note should be added to the read me 😄

**Comment by larpon** [comment]
Hey @AIIX I thought the `objdump` was working fine. What system and Qt setup are you running this from?  :)

**Comment by larpon** [comment]
Nah it was broken - would be nice with some more time so I could get this working
